name: render_publications


on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # This cron expression will run the workflow every 1st day of the month at midnight



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - uses: r-lib/actions/setup-pandoc@v2

    - name: Install curl
      run: sudo apt-get update && sudo apt-get install -y curl

    - name: Install cURL Headers
      run: sudo apt-get install libcurl4-openssl-dev

    - name: Install required packages
      run: Rscript -e "install.packages(c('rmarkdown','RCurl', 'XML', 'bibtex', 'RefManageR'))"

    - name: Set up API key
      run: echo "ZOTERO_API_KEY=${{ secrets.ZOTERO_API_KEY }}" >> .Renviron

    - name: Render publications
      run: Rscript -e "rmarkdown::render('publications/extract_zotero_bib.Rmd')"


    - name: Commit results
      run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit publications/index.md -m 'Re-build publications index.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"


